In [1]:
# Import Dependencies
import os
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
# View raw data files to aggregate
os.listdir('data/raw_data')

['201901-citibike-tripdata.csv',
 '201902-citibike-tripdata.csv',
 '201903-citibike-tripdata.csv',
 '201904-citibike-tripdata.csv',
 '201905-citibike-tripdata.csv',
 '201906-citibike-tripdata.csv',
 '201907-citibike-tripdata.csv',
 '201908-citibike-tripdata.csv',
 '201909-citibike-tripdata.csv',
 '201910-citibike-tripdata.csv',
 '201911-citibike-tripdata.csv',
 '201912-citibike-tripdata.csv']

In [3]:
# Tableau Public can work with a maximum of only 15,000,000 rows. The total rows for the full year of 
# 2019 is 20,523,930 so only the summer and winter months data will be used
# Read Citi Bike data into Pandas data frames
jan = pd.read_csv('data/raw_data/201901-citibike-tripdata.csv')
feb = pd.read_csv('data/raw_data/201902-citibike-tripdata.csv')
jun = pd.read_csv('data/raw_data/201906-citibike-tripdata.csv')
jul = pd.read_csv('data/raw_data/201907-citibike-tripdata.csv')
aug = pd.read_csv('data/raw_data/201908-citibike-tripdata.csv')
dec = pd.read_csv('data/raw_data/201912-citibike-tripdata.csv')

In [4]:
# Preview data frames
display(jan.head())
display(feb.head())
display(jun.head())
display(jul.head())
display(aug.head())
display(dec.head())

tripduration                 starttime                  stoptime  \
0           320  2019-01-01 00:01:47.4010  2019-01-01 00:07:07.5810   
1           316  2019-01-01 00:04:43.7360  2019-01-01 00:10:00.6080   
2           591  2019-01-01 00:06:03.9970  2019-01-01 00:15:55.4380   
3          2719  2019-01-01 00:07:03.5450  2019-01-01 00:52:22.6500   
4           303  2019-01-01 00:07:35.9450  2019-01-01 00:12:39.5020   

   start station id           start station name  start station latitude  \
0            3160.0  Central Park West & W 76 St               40.778968   
1             519.0        Pershing Square North               40.751873   
2            3171.0      Amsterdam Ave & W 82 St               40.785247   
3             504.0              1 Ave & E 16 St               40.732219   
4             229.0               Great Jones St               40.727434   

   start station longitude  end station id        end station name  \
0               -73.973747          3283.0  W 89 St & Columbus Ave   
1               -73.977706           518.0         E 39 St & 2 Ave   
2               -73.976673          3154.0         E 77 St & 3 Ave   
3               -73.981656          3709.0         W 15 St & 6 Ave   
4               -73.993790           503.0      E 20 St & Park Ave   

   end station latitude  end station longitude  bikeid    usertype  \
0             40.788221             -73.970416   15839  Subscriber   
1             40.747804             -73.973442   32723  Subscriber   
2             40.773142             -73.958562   27451  Subscriber   
3             40.738046             -73.996430   21579  Subscriber   
4             40.738274             -73.987520   35379  Subscriber   

   birth year  gender  
0        1971       1  
1        1964       1  
2        1987       1  
3        1990       1  
4        1979       1

tripduration                 starttime                  stoptime  \
0           219  2019-02-01 00:00:06.2570  2019-02-01 00:03:46.1090   
1           143  2019-02-01 00:00:28.0320  2019-02-01 00:02:51.7460   
2           296  2019-02-01 00:01:13.9870  2019-02-01 00:06:10.7340   
3           478  2019-02-01 00:01:14.1520  2019-02-01 00:09:12.7870   
4           225  2019-02-01 00:01:49.3410  2019-02-01 00:05:34.4980   

   start station id        start station name  start station latitude  \
0            3494.0  E 115 St & Lexington Ave               40.797911   
1             438.0       St Marks Pl & 1 Ave               40.727791   
2            3571.0   Bedford Ave & Bergen St               40.676368   
3             167.0           E 39 St & 3 Ave               40.748901   
4            3458.0           W 55 St & 6 Ave               40.763094   

   start station longitude  end station id        end station name  \
0               -73.942300          3501.0  E 118 St & Madison Ave   
1               -73.985649           236.0     St Marks Pl & 2 Ave   
2               -73.952918          3549.0   Grand Ave & Bergen St   
3               -73.976049           477.0         W 41 St & 8 Ave   
4               -73.978350          3443.0         W 52 St & 6 Ave   

   end station latitude  end station longitude  bikeid    usertype  \
0             40.801487             -73.944251   33450  Subscriber   
1             40.728419             -73.987140   25626  Subscriber   
2             40.678045             -73.962408   35568  Subscriber   
3             40.756405             -73.990026   25045  Subscriber   
4             40.761330             -73.979820   34006  Subscriber   

   birth year  gender  
0        1989       1  
1        1990       1  
2        1987       1  
3        1964       2  
4        1979       1

tripduration                 starttime                  stoptime  \
0           330  2019-06-01 00:00:01.5000  2019-06-01 00:05:31.7600   
1           830  2019-06-01 00:00:04.2400  2019-06-01 00:13:55.1470   
2           380  2019-06-01 00:00:06.0190  2019-06-01 00:06:26.7790   
3          1155  2019-06-01 00:00:06.7760  2019-06-01 00:19:22.5380   
4          1055  2019-06-01 00:00:07.5200  2019-06-01 00:17:42.5580   

   start station id       start station name  start station latitude  \
0              3602           31 Ave & 34 St               40.763154   
1              3054  Greene Ave & Throop Ave               40.689493   
2               229           Great Jones St               40.727434   
3              3771  McKibbin St & Bogart St               40.706237   
4               441          E 52 St & 2 Ave               40.756014   

   start station longitude  end station id       end station name  \
0               -73.920827            3570         35 Ave & 37 St   
1               -73.942061            3781  Greene Av & Myrtle Av   
2               -73.993790             326        E 11 St & 1 Ave   
3               -73.933871            3016      Kent Ave & N 7 St   
4               -73.967416            3159     W 67 St & Broadway   

   end station latitude  end station longitude  bikeid    usertype  \
0             40.755733             -73.923661   20348  Subscriber   
1             40.698568             -73.918877   34007  Subscriber   
2             40.729538             -73.984267   20587  Subscriber   
3             40.720368             -73.961651   33762  Subscriber   
4             40.774925             -73.982666   31290  Subscriber   

   birth year  gender  
0        1992       1  
1        1987       2  
2        1990       2  
3        1987       1  
4        1973       1

tripduration                 starttime                  stoptime  \
0           897  2019-07-01 00:00:00.1320  2019-07-01 00:14:58.0040   
1           267  2019-07-01 00:00:05.1780  2019-07-01 00:04:32.4500   
2          2201  2019-07-01 00:00:05.2130  2019-07-01 00:36:46.7490   
3          1660  2019-07-01 00:00:08.6010  2019-07-01 00:27:48.8050   
4           109  2019-07-01 00:00:12.1580  2019-07-01 00:02:01.5670   

   start station id       start station name  start station latitude  \
0             493.0          W 45 St & 6 Ave               40.756800   
1            3143.0          5 Ave & E 78 St               40.776321   
2             317.0        E 6 St & Avenue B               40.724537   
3             249.0  Harrison St & Hudson St               40.718710   
4            3552.0      W 113 St & Broadway               40.805973   

   start station longitude  end station id             end station name  \
0               -73.982912           454.0              E 51 St & 1 Ave   
1               -73.964274          3226.0  W 82 St & Central Park West   
2               -73.981854          3469.0           India St & West St   
3               -74.009001           369.0        Washington Pl & 6 Ave   
4               -73.964928          3538.0     W 110 St & Amsterdam Ave   

   end station latitude  end station longitude  bikeid    usertype  \
0             40.754557             -73.965930   18340  Subscriber   
1             40.782750             -73.971370   21458    Customer   
2             40.731814             -73.959950   39874  Subscriber   
3             40.732241             -74.000264   38865  Subscriber   
4             40.802692             -73.962950   30256  Subscriber   

   birth year  gender  
0        1966       1  
1        1996       1  
2        1986       1  
3        1988       1  
4        1997       1

tripduration                 starttime                  stoptime  \
0           393  2019-08-01 00:00:01.4680  2019-08-01 00:06:35.3780   
1           627  2019-08-01 00:00:01.9290  2019-08-01 00:10:29.7840   
2          1132  2019-08-01 00:00:04.0480  2019-08-01 00:18:56.1650   
3          1780  2019-08-01 00:00:04.1630  2019-08-01 00:29:44.7940   
4          1517  2019-08-01 00:00:05.4580  2019-08-01 00:25:23.4550   

   start station id              start station name  start station latitude  \
0             531.0          Forsyth St & Broome St               40.718939   
1             274.0  Lafayette Ave & Fort Greene Pl               40.686919   
2            2000.0        Front St & Washington St               40.702551   
3             479.0                 9 Ave & W 45 St               40.760193   
4            3312.0                 1 Ave & E 94 St               40.781721   

   start station longitude  end station id            end station name  \
0               -73.992663           408.0       Market St & Cherry St   
1               -73.976682          3409.0        Bergen St & Smith St   
2               -73.989402          3388.0     President St & Henry St   
3               -73.991255           473.0  Rivington St & Chrystie St   
4               -73.945940          3312.0             1 Ave & E 94 St   

   end station latitude  end station longitude  bikeid    usertype  \
0             40.710762             -73.994004   35305  Subscriber   
1             40.686744             -73.990632   38822  Subscriber   
2             40.682800             -73.999904   18373  Subscriber   
3             40.721101             -73.991925   25002  Subscriber   
4             40.781721             -73.945940   31198  Subscriber   

   birth year  gender  
0        1996       2  
1        1998       2  
2        1988       1  
3        1988       1  
4        1965       2

tripduration                 starttime                  stoptime  \
0           602  2019-12-01 00:00:05.5640  2019-12-01 00:10:07.8180   
1          1206  2019-12-01 00:00:10.9630  2019-12-01 00:20:17.8820   
2           723  2019-12-01 00:00:11.8180  2019-12-01 00:12:14.8310   
3           404  2019-12-01 00:00:12.2200  2019-12-01 00:06:56.8860   
4          1059  2019-12-01 00:00:14.7230  2019-12-01 00:17:54.1860   

   start station id      start station name  start station latitude  \
0              3382   Carroll St & Smith St               40.680611   
1               362      Broadway & W 37 St               40.751726   
2               146    Hudson St & Reade St               40.716250   
3              3834  Irving Ave & Halsey St               40.694670   
4               500      Broadway & W 51 St               40.762288   

   start station longitude  end station id              end station name  \
0               -73.994758            3304                  6 Ave & 9 St   
1               -73.987535             500            Broadway & W 51 St   
2               -74.009106             238       Bank St & Washington St   
3               -73.906630            3827          Halsey St & Broadway   
4               -73.983362            3323  W 106 St & Central Park West   

   end station latitude  end station longitude  bikeid    usertype  \
0             40.668127             -73.983776   41932  Subscriber   
1             40.762288             -73.983362   18869    Customer   
2             40.736197             -74.008592   15334  Subscriber   
3             40.685650             -73.915640   41692    Customer   
4             40.798186             -73.960591   40156  Subscriber   

   birth year  gender  
0        1970       1  
1        1999       1  
2        1997       1  
3        1995       1  
4        1961       1

In [5]:
# Separate words with "_" in column names to make them easier to read
col_names = ['trip_duration', 'start_time', 'stop_time', 'start_station_id', 'start_station_name', \
                 'start_station_latitude', 'start_station_longitude', 'end_station_id', \
                 'end_station_name', 'end_station_latitude', 'end_station_longitude', 'bike_id', \
                 'user_type', 'birth_year', 'gender']

jan.columns = col_names
feb.columns = col_names
jun.columns = col_names
jul.columns = col_names
aug.columns = col_names
dec.columns = col_names

In [6]:
# Check how many "-" values are in each data frame
print(jan[jan.isin(["-"])].count().sum())
print(feb[feb.isin(["-"])].count().sum())
print(jun[jun.isin(["-"])].count().sum())
print(jul[jul.isin(["-"])].count().sum())
print(aug[aug.isin(["-"])].count().sum())
print(dec[dec.isin(["-"])].count().sum())

0
0
0
0
0
0


In [7]:
# Replace infinity values with NaN
jan.replace([np.inf, -np.inf], np.nan, inplace=True)
feb.replace([np.inf, -np.inf], np.nan, inplace=True)
jun.replace([np.inf, -np.inf], np.nan, inplace=True)
jul.replace([np.inf, -np.inf], np.nan, inplace=True)
aug.replace([np.inf, -np.inf], np.nan, inplace=True)
dec.replace([np.inf, -np.inf], np.nan, inplace=True)

In [8]:
# Drop NaNs
jan.dropna(inplace=True)
feb.dropna(inplace=True)
jun.dropna(inplace=True)
jul.dropna(inplace=True)
aug.dropna(inplace=True)
dec.dropna(inplace=True)

In [9]:
# Check if data types for each corresponding column are the same among all data frames
# Concatenate all of the data frames to compare data types
data_types_df = pd.concat([jan.dtypes, feb.dtypes, jun.dtypes, jul.dtypes, aug.dtypes, dec.dtypes], \
                              axis=1)

# Rename columns to make the data frame easier to understand
data_types_df.columns = ['jan', 'feb', 'jun', 'jul', 'aug', 'dec']

# Check for inconsistent data types in corresponding columns
data_types_df

jan      feb      jun      jul      aug      dec
trip_duration              int64    int64    int64    int64    int64    int64
start_time                object   object   object   object   object   object
stop_time                 object   object   object   object   object   object
start_station_id         float64  float64    int64  float64  float64    int64
start_station_name        object   object   object   object   object   object
start_station_latitude   float64  float64  float64  float64  float64  float64
start_station_longitude  float64  float64  float64  float64  float64  float64
end_station_id           float64  float64    int64  float64  float64    int64
end_station_name          object   object   object   object   object   object
end_station_latitude     float64  float64  float64  float64  float64  float64
end_station_longitude    float64  float64  float64  float64  float64  float64
bike_id                    int64    int64    int64    int64    int64    int64
user_type                 object   object   object   object   object   object
birth_year                 int64    int64    int64    int64    int64    int64
gender                     int64    int64    int64    int64    int64    int64

In [10]:
# Data types consistency check conclusion:
# start_station_id and end_station_id columns' data types are inconsistent
# start_station_id - 4 data frames = float64, 7 data frames = int64
# end_station_id - 4 data frames = float64, 7 data frames = int64

# Solution: Convert the 4 float64 data frames to int64 since all start/end station IDs are whole numbers

In [11]:
# Convert the columns data types for consistency across all data frames
jan_converted = jan.astype({'start_station_id': np.int64, 'end_station_id': np.int64})
feb_converted = feb.astype({'start_station_id': np.int64, 'end_station_id': np.int64})
jul_converted = jul.astype({'start_station_id': np.int64, 'end_station_id': np.int64})
aug_converted = aug.astype({'start_station_id': np.int64, 'end_station_id': np.int64})

In [12]:
# Confirm matching data types
# Concatenate the converted data frames with the data frames that did not need to be converted to compare
# new data types
data_types_converted = pd.concat([jan_converted.dtypes, feb_converted.dtypes, jun.dtypes, \
                                  jul_converted.dtypes, aug_converted.dtypes, dec.dtypes], axis=1)

# Rename columns to make data frame easier to understand
data_types_converted.columns = ['jan', 'feb', 'jun', 'jul', 'aug', 'dec']

# Confirm matching data types
data_types_converted

jan      feb      jun      jul      aug      dec
trip_duration              int64    int64    int64    int64    int64    int64
start_time                object   object   object   object   object   object
stop_time                 object   object   object   object   object   object
start_station_id           int64    int64    int64    int64    int64    int64
start_station_name        object   object   object   object   object   object
start_station_latitude   float64  float64  float64  float64  float64  float64
start_station_longitude  float64  float64  float64  float64  float64  float64
end_station_id             int64    int64    int64    int64    int64    int64
end_station_name          object   object   object   object   object   object
end_station_latitude     float64  float64  float64  float64  float64  float64
end_station_longitude    float64  float64  float64  float64  float64  float64
bike_id                    int64    int64    int64    int64    int64    int64
user_type                 object   object   object   object   object   object
birth_year                 int64    int64    int64    int64    int64    int64
gender                     int64    int64    int64    int64    int64    int64

In [13]:
# Confirm 'user_type' column has only two unique values: "Customer" and "Subscriber"
print(jan_converted['user_type'].unique())
print(feb_converted['user_type'].unique())
print(jun['user_type'].unique())
print(jul_converted['user_type'].unique())
print(aug_converted['user_type'].unique())
print(dec['user_type'].unique())

['Subscriber' 'Customer']
['Subscriber' 'Customer']
['Subscriber' 'Customer']
['Subscriber' 'Customer']
['Subscriber' 'Customer']
['Subscriber' 'Customer']


In [14]:
# Confirm 'gender' column in each data frame has only three unique values: "0", "1", and "2"
print(jan_converted['gender'].unique())
print(feb_converted['gender'].unique())
print(jun['gender'].unique())
print(jul_converted['gender'].unique())
print(aug_converted['gender'].unique())
print(dec['gender'].unique())

[1 2 0]
[1 2 0]
[1 2 0]
[1 2 0]
[2 1 0]
[1 2 0]


In [15]:
# Aggregate all data
all_data = pd.concat([jan_converted, feb_converted, jun, jul_converted, aug_converted, dec])

In [16]:
# Preview aggregated data frame
all_data.head()

trip_duration                start_time                 stop_time  \
0            320  2019-01-01 00:01:47.4010  2019-01-01 00:07:07.5810   
1            316  2019-01-01 00:04:43.7360  2019-01-01 00:10:00.6080   
2            591  2019-01-01 00:06:03.9970  2019-01-01 00:15:55.4380   
3           2719  2019-01-01 00:07:03.5450  2019-01-01 00:52:22.6500   
4            303  2019-01-01 00:07:35.9450  2019-01-01 00:12:39.5020   

   start_station_id           start_station_name  start_station_latitude  \
0              3160  Central Park West & W 76 St               40.778968   
1               519        Pershing Square North               40.751873   
2              3171      Amsterdam Ave & W 82 St               40.785247   
3               504              1 Ave & E 16 St               40.732219   
4               229               Great Jones St               40.727434   

   start_station_longitude  end_station_id        end_station_name  \
0               -73.973747            3283  W 89 St & Columbus Ave   
1               -73.977706             518         E 39 St & 2 Ave   
2               -73.976673            3154         E 77 St & 3 Ave   
3               -73.981656            3709         W 15 St & 6 Ave   
4               -73.993790             503      E 20 St & Park Ave   

   end_station_latitude  end_station_longitude  bike_id   user_type  \
0             40.788221             -73.970416    15839  Subscriber   
1             40.747804             -73.973442    32723  Subscriber   
2             40.773142             -73.958562    27451  Subscriber   
3             40.738046             -73.996430    21579  Subscriber   
4             40.738274             -73.987520    35379  Subscriber   

   birth_year  gender  
0        1971       1  
1        1964       1  
2        1987       1  
3        1990       1  
4        1979       1

In [17]:
# Confirm the ages in the data make sense
print(f'Youngest rider\'s age and birth year in the data: \
        {max(all_data["birth_year"])}, {2019 - max(all_data["birth_year"])}')
print(f'Oldest rider\'s age and birth year in the data: \
        {min(all_data["birth_year"])}, {2019 - min(all_data["birth_year"])}')



# Use the below code if you want the age confirmations to update every year, but the Tableau data story is based on the 
#     year 2019
# print(f'Youngest rider\'s age and birth year in the data: \
#         {max(all_data["birth_year"])}, {datetime.now().year - max(all_data["birth_year"])}')
# print(f'Oldest rider\'s age and birth year in the data: \
#         {min(all_data["birth_year"])}, {datetime.now().year - min(all_data["birth_year"])}')

Youngest rider's age and birth year in the data:         2003, 16
Oldest rider's age and birth year in the data:         1885, 134


In [18]:
# Oldest age, 134 years (as of 2019), does not make sense so 'birth_year' column will be filtered
# Google search returns several articles discussing increase in U.S. bike trips by seniors through age 79
# so 79 years will be maximum age for Citi Bike data
all_data = all_data[all_data['birth_year'] >= 1940]

In [19]:
# Confirm total rows <= 15,000,000 to make sure Tableau Public will be able to work with this data
all_data['birth_year'].count()

9503955

In [20]:
# Export aggregated data to csv file
all_data.to_csv('data/citi_bike_summer_winter_2019.csv', sep=',', index=False)